STEP:         10                    #time cycle in milliseconds
PIPE:         plcpipe                 #UNIX path of named pipe polled for commands
RESPONSE:     plcresponse                 #>>  named pipe for response
SIGENABLE:     36                     #POSIX enable signal which is used to lock/unlock the interface.
PAGELEN:        24                    #max screen length in characters.
PAGEWIDTH:     80                    #>> width
NT:         16                     #number of timers
NS:         16                    #number of blinking timers
NM:         32                     #number of internal memory registers 

#hardware
HW:         STDI/O                #just a text tag that appears in a footer
DI:         4                     #number of bytes of digital inputs
DQ:         4                     #number of bytes of digital outputs

#user space interface:
USPACE: 
    BASE:         50176             #hardware address base
    WR_OFFS:        4                #write offset
    RD_OFFS:        0                #read offset

#COMEDI interface:
COMEDI: 
    FILE:     0            #device and subdevice nodes of comedi driver.
    SUBDEV: 
        Input: 0
        Output: 1
    
#SIMULATION IO
SIM: 
    INPUT:   sim.in
    OUTPUT:  sim.out

#PROGRAM    
DI:
    -Index: 0
    Identifier: A
    -Index: 1
    Identifier: B
    
DQ: 
    -Index: 0
    Identifier: OUTPUT
        

MREG:
    -Index: 0
    Identifier: RESULT
    Value: 64   
    
    -Index: 1
    Identifier: TEMP
          
IL: "gcd.il"    





































