STEP:         10        #time cycle in milliseconds
PIPE:         plcpipe   #UNIX path of named pipe polled for commands
NT:         16            #number of timers
NS:         16            #number of blinking timers
NM:         32            #number of internal variables

#hardware
HW:         STDI/O                #just a text tag that appears in a footer
DI:         4                     #number of bytes of digital inputs
DQ:         4                     #number of bytes of digital outputs

#user space interface:
USPACE: 
    BASE:         50176            #hardware address base
    WR_OFFS:        4               #write offset
    RD_OFFS:        0                #read offset


#COMEDI interface:
COMEDI: 
    FILE:     0,           #device and subdevice nodes of comedi driver.
    SUBDEV: 
        Input: 0
        Output: 1
    

#SIMULATION IO
SIM: 
    INPUT:   sim.in
    OUTPUT:  sim.out

#PROGRAM    
DI:
    -INDEX: 0
    ID:    A    
    -INDEX: 1
    ID:    B    
    -INDEX: 2
    ID:    C        
 
DQ:
    -INDEX: 0
    ID:    RESULT

TIMER:
    -INDEX: 1
    RESOLUTION: 10
    PRESET: 10
            

PULSE:
    -INDEX: 1    
    RESOLUTION: 100    


# triple majority circuit
# https://en.wikipedia.org/wiki/Triple_modular_redundancy

LD: "triple_majority.ld"


